version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: example_db
      WORDPRESS_DB_USER: example_user
      WORDPRESS_DB_PASSWORD: example_password
    depends_on:
      - mysql
    volumes:
      - wordpress_data:/var/www/html  # Đảm bảo volume đã được định nghĩa

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  wordpress_data:  
  mysql_data: