version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Mật khẩu cho tài khoản root
      MYSQL_USER: user                   # Tên người dùng
      MYSQL_PASSWORD: password           # Mật khẩu cho người dùng
      MYSQL_DATABASE: mydb               # Tên cơ sở dữ liệu mặc định
    ports:
      - "3306:3306"                       # Ánh xạ cổng 3306 của container với cổng 3306 của máy chủ
    volumes:
      - mysql_data:/var/lib/mysql        # Dữ liệu của MySQL được lưu trữ vào volume ngoài container

volumes:
  mysql_data:
    driver: local
