version: '3.8'

services:
  mongodb:
    image: mongo:latest  # Sử dụng image MongoDB mới nhất từ Docker Hub
    container_name: mongo-db
    ports:
      - "27017:27017"   # Ánh xạ cổng 27017 của MongoDB từ container ra máy chủ
    volumes:
      - mongodb-data:/data/db  # Lưu trữ dữ liệu MongoDB vào volume ngoài container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Tên người dùng admin
      MONGO_INITDB_ROOT_PASSWORD: example  # Mật khẩu cho người dùng admin

  mongo-express:
    image: mongo-express:latest  # Sử dụng image Mongo Express mới nhất từ Docker Hub
    container_name: mongo-express
    ports:
      - "8081:8081"   # Ánh xạ cổng 8081 của Mongo Express từ container ra máy chủ
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb  # Địa chỉ MongoDB service
      ME_CONFIG_MONGODB_ADMINUSERNAME: root  # Tên người dùng admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: example  # Mật khẩu admin cho MongoDB
      ME_CONFIG_SITE_BASEURL: /mongo-express  # URL gốc của Mongo Express
    depends_on:
      - mongodb  # Đảm bảo Mongo Express sẽ được khởi động sau khi MongoDB đã sẵn sàng

volumes:
  mongodb-data:
    driver: local
